spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.10.46:3306/GoGo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  data:
    redis:
      host: 8.130.10.46
      port: 6379
      password: zlh123456
      database: 1
#      jedis:
#        pool:
#          max-active: 8
#          max-wait: 1ms
#          max-idle: 4
#          min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

edu-system:
  url: https://jwxt.hbwe.edu.cn

